# Generated by Django 4.1.3 on 2022-11-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Venue Name')),
                ('card', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
