# Generated by Django 4.1.3 on 2022-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_aadhar_back_aadhar_front_delete_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar_back',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aadhar_front',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
