# Generated by Django 4.1.3 on 2022-11-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_aadhar_back_name_aadhar_front_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhar_back',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aadhar_front',
            name='name',
        ),
    ]
